meta_product_name: "Rent a Boat"
meta_title: "Rent a Boat"
meta_description: "Easilybook a boat for your next trip"
meta_image: "cover.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
